version: "3.9"

services:
  traefik:
    image: traefik:v3
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --api.dashboard=true
    ports:
      - "8081:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yml:/traefik.yml
    restart: always

  postgres:
    image: postgres:15
    env_file:
      - ../env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
