services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ../iot/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ../iot/mosquitto/data:/mosquitto/data
      - ../iot/mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.8.0
    restart: unless-stopped
    depends_on:
      - mosquitto
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    expose:
      - "8080"
    volumes:
      - ../iot/zigbee2mqtt/data:/app/data
    environment:
      - TZ=Europe/Amsterdam
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee.rule=Host(`zigbee.home`)"
      - "traefik.http.services.zigbee.loadbalancer.server.port=8080"

networks:
  default:
    external: true
    name: infra
